baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Geekdoc Site"
theme = "hugo-geekdoc"

pygmentsUseClasses = true
pygmentsCodeFences = true
enableGitInfo = true
enableRobotsTXT = true
[pagination]
  pagerSize = 20


[params]
  geekdocRepo = "https://github.com/yourname/your-repo"
  geekdocEditPath = "edit/main/content"
  geekdocDateFormat = "Jan 2, 2006"
  geekdocSearch = true

